#cloud-config

package_update: true

package_upgrade: true

timezone: 'Europe/Amsterdam'

yum_repos:
  elasticsearch:
    name: Elasticsearch repository for 6.x packages
    baseurl: https://artifacts.elastic.co/packages/6.x/yum
    gpgcheck: true
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    enabled: true
    autorefresh: true
    type: rpm=md

packages:
- java-1.8.0
- nginx
- git
- elasticsearch
- zsh

write_files:
  - path: /home/ec2-user/.zshrc
    permissions: '0644'
    content: |
      zstyle :compinstall filename '/home/ec2-user/.zshrc'

      autoload -Uz compinit
      compinit
  - path: /root/.gitconfig
    permissions: '0644'
    owner: root:root
    content: |
      [credential]
        helper = !aws codecommit credential-helper $@
        UseHttpPath = true
  - path: /etc/nginx/nginx.conf
    permissions: '0644'
    owner: root:root
    content: |
      events {
        worker_connections 1024;
      }

      http {
        server {
          listen 80;
          location / {
            proxy_pass http://127.0.0.1:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          }
        }
      }

runcmd:
  - yum remove java-1.7.0-openjdk -y
  - sed -i 's|/bin/bash|/bin/zsh|g' /etc/passwd
  - aws ec2 associate-address --allocation-id ${allocation_id} --instance-id `curl http://169.254.169.254/latest/meta-data/instance-id` --region ${region}
  - chkconfig --add elasticsearch
  - service elasticsearch start
  - chkconfig --add nginx
  - service nginx start
  - export HOME=/root
  - export PROJECT_DIR=$HOME/project
  - cd $HOME
  - git clone ${repo} $PROJECT_DIR
  - pip install -r $PROJECT_DIR/requirements.txt
  - aws s3 cp ${source_s3_path} $PROJECT_DIR/files/${source_filename}
  - python $PROJECT_DIR/scripts/initialize.py
  - python $PROJECT_DIR/scripts/import.py $PROJECT_DIR/files/${source_filename}
  - /usr/local/bin/gunicorn --chdir $PROJECT_DIR/api -w 4 app:app &

final_message: "The system is finally up, after $UPTIME seconds"
