resource "aws_key_pair" "elasticsearch" {
  key_name   = "elasticsearch"
  public_key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDfLvP9e/DWQFw/of4oNEVWL3y5LetYSINM0fwtCBDsFXfOQ+JlElfZinU5R0bLA7FiLQHJfRiN0YGwuj2kfrkW+pZ9XFYGDvPEeF9GomJtzGM4heUhVr1CAurZYUAlF6AsfIGamZVUkp/ClpTgVvvTJ2BK2PPbqeFCWS0beiSorja0AjfqXf3J2KBI7zUP5leQENh75Qbk8kXISzCYZ64QplNTWM6oFIkbnz8/FatETJBfZl/oer/UZPngmtmvM7uXeqOiGhjyYs1sY6JO10OYkJL6gml/mJSbKbHkJkYy/PQQF6+d5nB9AdfPYUEYESKZiTOelINTf1xF/f6LZZfZ mark@biesheuvel.amsterdam"
}
